name: CI/CD - validate & deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # validate:
  #   name: HTML Validate
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #     - name: Install html-validate
  #       run: npm install -g html-validate
  #     - name: Run html-validate
  #       run: html-validate --config .htmlvalidate.json index.html || exit $?

  deploy:
    name: Deploy to GitHub Pages
    # needs: validate
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            index.html
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
